### ISSUE TITLE
Entries field doesn't appear to work

### ISSUE THREAD

**Issue by andyharris** [engram-design/SuperTable#11]
Hi - I'm having problems getting an entries field to work within SuperTable, when it's used in a matrix.

The first way I tried was a typical body matrix field (content, image, quote, links) with the idea being that they could insert a series of links within the body using a SuperTable - fields in SuperTable were icon (dropdown), text (text!) and link (entries).

![pasted_image_at_2015_05_29_10_54_am_1024](https://cloud.githubusercontent.com/assets/49345/8351304/3c959d4c-1b24-11e5-9dd5-62090278f52d.png)

Icon and text work perfectly, but the entries loop doesn't work (the "else" conditional in the "for" loop fired, in fact)

![pasted_image_at_2015_05_29_10_54_am_1024-1](https://cloud.githubusercontent.com/assets/49345/8351307/432929f8-1b24-11e5-802e-6603295cb445.png)

Cheers!
Andy.

**Comment by engram-design** [comment]
Interesting. I'd hazard a guess this is because `link` is a reserved handle. Validation was added for the field in the last round of updates, but after testing this just now, looks as though you can get away with this when a Super Table field is inside a Matrix field.

If you could - would you try renaming the Link handle? Just want to confirm this is the issue...

**Comment by andyharris** [comment]
I just came back here to update this! That is exactly what it was, all is working well.

Embarrassingly, I think I may have even reported the original problem with using link too. Thanks though!

**Comment by engram-design** [comment]
Nah all good - you've actually picked up a bit of a bug, so thanks! :smile:
