### ISSUE TITLE
JS Errors on Matrix Creation

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/SuperTable#13]
I am getting a bunch of strange JS errors when I use a matrix within a matrix. I will document more later - working on a deadline but wanted to give a heads up!

**Comment by engram-design** [comment]
Interested to see what these errors are, so when you can, shoot them through. I know there is an issue when adding a Super Table field inside a Matrix block, adding a new block, then adding a new Super Table field to that block. There are some tricky namespacing issues that collide between the Matrix JS and Super Table JS.

One way to get around this is to save the field, go back in, create a new block and add your Super Table field. It's tedious, but it works! Just means you have to create Matrixs blocks (if they have a Super Table in it) one at a time.

**Comment by theskyfloor** [comment]
Still have to write this up. The error I was having is similar to the one you describe here but seems to have a peskier presentation.

**Comment by theskyfloor** [comment]
Here is this issue in brief... once I have created the SuperTable and Matrix within a Matrix and saved on subsequent attempts to add additional fields to the original parent matrix results in fields being added twice which then causes an error on save - the only way to defeat this bug is to temporarily disable `SuperTableConfigurator.js` and create the new field - then enable it again so you can still edit the supertable field.

![screen shot 2015-07-16 at 2 30 27 pm](https://cloud.githubusercontent.com/assets/8887839/8733125/9aba1de0-2bc7-11e5-88ff-29c3605f96f9.png)

**Comment by engram-design** [comment]
@theskyfloor Thanks again for the detailed case. I'm aware of these issues, but its a tricky situation, as these errors are actually caused by the Matrix field JS implementation. Currently, it doesn't like it when there are more than one Matrix Configurator's on one page. This is fair enough, because P&T don't support Matrix-in-Matrix.

I'll need to see if they'll be open to altering their JS bindings to bind to a unique element. In case you're interested, this is because of this single line in `MatrixConfigurator.js:48`

```
this.$container = $('.matrix-configurator:first .input:first');
```

**Comment by engram-design** [comment]
@theskyfloor The latest Craft build [Craft 2.4.2677](https://buildwithcraft.com/updates#build2677) included some Matrix-related fixes. This should fix a few of the javascript issues with Super Table and Matrix.
