### ISSUE TITLE
Usage of "reserved" keywords like 'title' and 'link' as field names?

### ISSUE THREAD

**Issue by FreekVR** [engram-design/SuperTable#140]
With Craft 3, I am running into issues with using fieldnames like 'title' and 'link' within a super table. Craft never gives any error about using these field names, but when using them in templates like {{ contentBlock.link }} it seems to map to an internal function or attribute on the SuperTable model rather than the field.

What is the best practice here?

**Comment by engram-design** [comment]
`title` and `link` have always been reserved field handles for fields, whether they're on their own, in a Matrix field, or in a Super Table field. This is because they're used to refer to attributes on the element (Entry) that you're on. As such, Craft doesn't know if you want the `link` attribute of the element, or a custom field called that.

Do you not see the validation message when trying to create a normal field?
![screen shot 2018-04-05 at 10 38 10 am](https://user-images.githubusercontent.com/1221575/38341788-b2691ecc-38bd-11e8-8d37-b102aa367f11.png)

**Comment by FreekVR** [comment]
Yeah, I do get it when I create a normal field, but not when I create a field within a super table.

The first screenshot is creating a vanilla Craft field, the second is creating a field within a SuperTable Block (which is nested in a matrix field, not sure if that matters)

![screen shot 2018-04-05 at 11 21 43](https://user-images.githubusercontent.com/417416/38357821-f11428b4-38c3-11e8-8a2a-c3bcde24be9e.png)
![screen shot 2018-04-05 at 11 23 59](https://user-images.githubusercontent.com/417416/38357822-f1291f1c-38c3-11e8-9639-3558e1423a1b.png)

So it should either use the same validation or simply work in the front-end, but currently it does neither ;)

**Comment by engram-design** [comment]
Ah yes, that's the critical thing Matrix > Super Table combinations is the issue here. I'll see what can be done to mitigate this, as validation is controlled by the parent Matrix field.

**Comment by engram-design** [comment]
Fixed in [2.0.6](https://github.com/verbb/super-table/releases/tag/2.0.6).
