### ISSUE TITLE
Override Super Table styles in CP

### ISSUE THREAD

**Issue by rogertinch** [engram-design/SuperTable#211]
### Description
I really love the functionality of Super Table, but I'm always bothered by its visual inconsistency in how it displays tables, rows and columns when compared against other fields of that type. Anything in the roadmap to update the look so it's more insync with the Craft CP styleguide or to allow for styling overrides?

Here's my bad attempt in trying to style a Super Table Row Layout to match the table look of Pixel & Tonic's Store Hours fieldtype:
![screen shot 2018-11-01 at 10 50 35 am](https://user-images.githubusercontent.com/11000310/47862828-fb57da00-ddc3-11e8-89ea-5af00b5bba3f.png)

**Comment by engram-design** [comment]
Are we talking mostly colour and fonts here? Granted, this did change in Craft 3 where everything went from grey to a little more blue. I've updated the styles to reflect this.

https://github.com/verbb/super-table/releases/tag/2.0.12

Otherwise, your best bet is to use [CPCSS](https://github.com/doublesecretagency/craft-cpcss).

Let me know if there's anything else you'd like to add!
