### ISSUE TITLE
Column width for table layout doesn't work

### ISSUE THREAD

**Issue by richhayler** [engram-design/SuperTable#221]
### Description
When configuring the columns of the field there is a width option but it doesn't appear to do anything despite specifying a width either in px or %.

Additionally the width field only appears after saving the superTable field.

**Comment by richhayler** [comment]
Width appears to be working now so not sure why I as seeing this beforehand. The issue with the width option not appearing when creating the supertable field is still there though. I am seeing this when creating a super table within a matrix.

**Comment by engram-design** [comment]
Glad to hear width worked out for you in the end, that certainly should be working.

The second part is a little more complicated unfortunately (having width shown before the Super Table field is saved). The reason for this is that the way that this content is stored alongside regular field content.

If you have a Super Table field, with a text field, you'll be able to set the name, handle, etc on that field - that's just a regular old plain text field. We can't add any further information to this field other than what Craft lets us do, so we need to come up with another way to store this width value. Our solution is to store it on the Super Table field as an array, indexed by the field's ID.

So, it'd be stored in the Super Table field settings as `columns: { 123: { width: '22px' } }`.

Now if this is on a new field, we obviously don't have an ID to store against this content, and using the field handle is too unreliable.

So that's the long-winded answer why it isn't there - its not great, but there's not a great solution otherwise. Our best bet would be if Craft didn't freak out if we stored additional content in a field's settings. Right now, if we try to save a `width` value in the plain text fields' settings, we'll get a `Setting unknown property: craft\fields\PlainText::width`. One day I'll see what we can do about this!
