### ISSUE TITLE
Collapsed Matrix blocks inside of SuperTable stretch way outside of the canvas

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/SuperTable#24]
As you can see on the right hand side of this image the Matrix block exceeds the SuperTable container when it is collapsed and only when it is collapsed. Another issue I am running into is that click on the Matrix block headline jumps me down the page... seems to be an anchor tag sort of behavior - although it might be in the Craft Matrix code and have nothing to do with ST.

![screen shot 2015-08-08 at 2 21 40 pm](https://cloud.githubusercontent.com/assets/8887839/9151850/f2db5714-3dd8-11e5-9e08-63d80ba107fb.png)

**Comment by theskyfloor** [comment]
Oh interesting - it seems to be because the Matrix block is trying to preview all of the field content - and since it is many paragraphs of text it is running outside of the frame.

**Comment by ChaseGiunta** [comment]
Might be worth tinkering with this, with the CPCSS plugin as a temporary fix. Is this a SuperTable specific problem?

**Comment by engram-design** [comment]
@theskyfloor @ChaseGiunta Yeah, its something that we can fix, its due to the field's `table` being set to `table-layout: auto;`, and can be sorted by setting it to `table-layout: fixed;`. But this messes up the auto-width for the first column (the one with the column/row heading). While I can set these to be fixed-width, it was kinda handy having them fluid.

I'll have a look at changing this, but if one of your guys can put together some better css to take care of this, by all means go ahead :smiley:

**Comment by engram-design** [comment]
Fixed in the [0.3.4](https://github.com/engram-design/SuperTable/releases/tag/0.3.4)
