### ISSUE TITLE
fieldGroup missing in project.yaml for supertable fields after upgrade from 3.0 to 3.1

### ISSUE THREAD

**Issue by nettum** [engram-design/SuperTable#252]
### Description
fieldGroup is missing from `project.yaml` under fields for super table fields, e.g:
```
fields:
  ...
  61b3f5d6-035c-4186-bf93-b1e80920f586:
    settings:
      columns:
        79:
          width: ''
        80:
          width: ''
        81:
          width: ''
        82:
          width: ''
        83:
          width: ''
      contentTable: '{{%stc_18_links}}'
      fieldLayout: row
      localizeBlocks: false
      maxRows: ''
      minRows: '2'
      selectionLabel: 'Legg til flere lenker'
      staticField: ''
```

This will result in an error when running `./craft setup` on a fresh craft install:
```
Exception 'craft\errors\MigrationException' with message 'An error occurred while executing the "craft\migrations\Install migration: Undefined index: fieldGroup'

in .../vendor/craftcms/cms/src/db/MigrationManager.php:260
```
Check Content Tables says no error and the fieldGroup does not seem to get fixed if I run "Re-save Fields"

I've tried to start with a fresh craft 3.1 install and creating supertable fields (inside a matrix and as a standalone). In this occasion it seems to be synced nicely, so this seems to be related to migration from 3.0 to 3.1?

### Additional info

- Plugin version: 2.1.15
- Craft version: 3.1.15

**Comment by engram-design** [comment]
Should be fixed in [2.1.16](https://github.com/verbb/super-table/releases/tag/2.1.16) as part of the migration. But you'll need to delete the Super Table fields in your project config manually.

FYI, I believe this issue is for Super Table fields nested in a Matrix field - the fields are setup correctly, but the Super Table field is stored in the `fields` section of the project config, where they shouldn't be (they belong to the Matrix field). As such, I believe they can be safely removed.
