### ISSUE TITLE
Migrating from Craft 2 to 3.1 Super Table within Matrix loses data

### ISSUE THREAD

**Issue by jamesmacwhite** [engram-design/SuperTable#255]
### Description

This is similar to #250. I have a Super Table within a Matrix field which has two blocks within.

* Block heading - Plain Text
* Block body - Redactor

![image](https://user-images.githubusercontent.com/8067792/54679232-a90f1f80-4afe-11e9-8f40-5b722184c8b5.png)

![image](https://user-images.githubusercontent.com/8067792/54679531-6b5ec680-4aff-11e9-98b1-af4204daaf37.png)

From a Craft 2 to 3.1 migration I am seeing the data not migrated, the count of blocks within seems to be maintained on entries, but they are all empty:

![image](https://user-images.githubusercontent.com/8067792/54679754-08216400-4b00-11e9-8c1c-29d0f61df6cc.png)

Any ideas?

### Additional info

- Plugin version: 2.1.16
- Craft version: 3.1.19

**Comment by engram-design** [comment]
I assume there were no errors during the migration? I've seen this before with Redactor (and other plugins), but it should be taken care of during migration.

Have you run the [Content Table checker](https://github.com/verbb/super-table#craft-31-changes)?

**Comment by jamesmacwhite** [comment]
No errors during migration. If anything it looks like the migration appears to have at least handled part of field because the equal amount of blocks within the field are present, just the data within missing.

Ah! That's handy, sorry I should of seen that in the docs. Running the Content Table Checker, it shows signs of things not being so healthy!

```
> ERROR: Super Table field #128 is missing its content table in settings ...
> ERROR: Super Table field #25 is missing its content table in settings ...
> ERROR: Super Table field #29 is missing its content table in settings ...
> ERROR: Shortened table not found. craft_supertablecontent_accordion should be craft_stc_accordion ...
> ERROR: Shortened table not found. craft_supertablecontent_links should be craft_stc_links ...
> ERROR: #25 has inconsistent field settings in its project config ...
> ERROR: #29 has inconsistent field settings in its project config ...
> ERROR: #93 has inconsistent field settings in its project config ...
```

However, my local dev environment (nanobox) doesn't have `mysqldump`, so the fix process errors out with `Shell Command Failure – craft\errors\ShellCommandException`. I'll sort out mysqldump and try the fix option and let you know how it goes!

**Comment by jamesmacwhite** [comment]
I've been having some interesting issues with the fix process on my local dev, but I believe that be something with Craft itself, because the mysqldump shell command process isn't happy on my Windows hosted Nanobox environment.

However, I went got gold and ran it our staging environment which is full Linux and the fix process seems to remedy field data in question, so I'll note this in my ever growing `MIGRATION-CRAFT3.md`!

**Comment by mcclaskiem** [comment]
I just wanted to surface experiencing a similar issue with a Migration i just did of `2.7.x` to `3.1.x`. After importing my Craft 2 Database into my Craft 3 install, I performed all the necessary database updates with no errors. I then viewed my entries and saw that wherever a Super Table field was nested inside of a Matrix, it maintained that that matrix block existed by had no reference of the SuperTable.

Attached is a screenshot of my database tables:
![Screen Shot 2020-12-07 at 12 25 33 PM](https://user-images.githubusercontent.com/6970287/101384096-fa89b000-3887-11eb-8691-7c7da9d07641.png)

It looks like the migration ended up creating all new tables and when using the "Re-Save" helper inside the CP, the issue is not fixed. I then renamed the tables to the below, where `_1` is the "old" tables and `_new` is the ones that were made during the migration.
![Screen Shot 2020-12-07 at 12 31 28 PM](https://user-images.githubusercontent.com/6970287/101384295-3de41e80-3888-11eb-8854-2829a476faf5.png)

After making this change, it appears as though my fields are working properly and pulling in the old data. Did I do something wrong during my migration?
