### ISSUE TITLE
SQL exception

### ISSUE THREAD

**Issue by pette87** [engram-design/SuperTable#256]
### Description

After save I try a error. Log file:

PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deletedWithOwner' in 'field list'

### Steps to reproduce

1. delete a item in table and then click save

### Additional info

- Plugin version: 2.1.16
- Craft version: 3.1.19

**Comment by engram-design** [comment]
Was this a (recent) upgrade? This should've been taken care of during a migration, and wondering if there were any error in the latest upgrade to Craft and/or plugins?

**Comment by pette87** [comment]
Yes, it was a recent upgrade. There was no error during the upgrade. Is there a solution?

**Comment by pette87** [comment]
> Was this a (recent) upgrade? This should've been taken care of during a migration, and wondering if there were any error in the latest upgrade to Craft and/or plugins?

Can you help?

**Comment by engram-design** [comment]
In your `migrations` database table, does `m190117_000000_soft_deletes` exist?

You could manually add that column to the `supertableblocks` table, or I can tag another release with the migration duplicated, but just trying to figure out why this migration wasn't run.

Did you upgrade from Craft 2, or Craft 3.0?

**Comment by matthillco** [comment]
I get the same errors when I try to delete any entries that use Supertable fields. This has been a problem since using it on a new Craft 3 project which has been steadily upgraded to every update. I'm now running Craft 3.1.21.

I have the `m190117_000000_soft_deletes` in my migrations table. But there's no `deletedWithOwner` column in my `supertableblocks` table. I do have some `stc_xxxxxx` tables for supertable fields that I've since deleted - should I delete these?

I tried running the Check Content Tables function, and receive one error: `ERROR: #97 has inconsistent field settings in its project config ...` but when I click Fix, the shell command fails because the mysqldump command can't be found (I suspect this is a Windows path problem, I've seen this before when Craft can't backup the database).

I'm running on Wampserver 3 on Windows, (PHP 7.2.4, Apache 2.4.37, MySQL 5.7.24).

**EDIT**: I was able to fix the Check Content Tables / Resave functions by adding mysql to my Windows path. However, deleting an entry with Supertables still fails with an SQL error:

```
Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deletedWithOwner' in 'field list'
The SQL being executed was: UPDATE `supertableblocks` SET `deletedWithOwner`=TRUE WHERE `id`='544'
Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'deletedWithOwner' in 'field list'
)
↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deletedWithOwner' in 'field list'
in E:\Repos\xxxxxx\site\craftcms\vendor\yiisoft\yii2\db\Command.php at line 1290
```

**Comment by engram-design** [comment]
Yep, so the fixer does need mysqldump to work, as it takes a backup before doing anything - just in case. Glad you've solved that.

I'm honestly stuck as why that database column is missing if the migration has run successfully. This is the very thing that adds that column. You can manually run the following query to rectify the missing column:

```
ALTER TABLE `supertableblocks` ADD `deletedWithOwner` tinyint(1) DEFAULT NULL AFTER sortOrder;  
```

**Comment by matthillco** [comment]
Great, thanks for that: adding the column does fix everything. I guess we'll never know why that column was missing, but at least now I can use Supertable again :)

**Comment by engram-design** [comment]
Hmmm, going to close this for the moment, but if anyone has this issue in the future, we'll reopen this...
