### ISSUE TITLE
Unable to find the template “_components/fieldtypes/Assets/input”.

### ISSUE THREAD

**Issue by thulstrup** [engram-design/SuperTable#297]
### Description

After updating Craft I'm unable to create or edit any content in the admin interface.

Craft throws an error:
Twig Template Loading Error – craft\web\twig\TemplateLoaderException
Unable to find the template “_components/fieldtypes/Assets/input”
at line 27 of vendor/verbb/super-table/src/templates/field.html

### Additional info

- Plugin version: 2.2.1
- Craft version: 3.3.1.2

**Comment by joshuabaker** [comment]
Somehow the template mode is ending up as `site`, instead of `cp`, when trying to render that template.

Following the web of calls, it looks like there’s a suppressed exception somewhere in the view component, which is preventing the `View::setTemplateMode` from restoring the correct template mode.

**Comment by nstcactus** [comment]
The regression was introduced in 3.3.1.1. A temporary workaround is to downgrade Craft. I had no troubles with project-config when I did so.

**Comment by engram-design** [comment]
Thanks for reporting, I'll get up to the latest version and test as soon as I can

**Comment by joshuabaker** [comment]
Reverting to `3.3.1.1` worked. Thanks, @nstCactus 🙏

**Comment by engram-design** [comment]
So, just testing on 3.3.1.2, and I can't seem to recreate this issue. I've tested editing/creating Super Table field, editing/creating entries with Super Table fields attached to them, but all seems okay?

I wonder if its another plugin incorrectly settings the templateMode, before Super Table? Would have to be something common to 3 people though!

**Comment by thulstrup** [comment]
Here are my plugins:
- Cookies
- Feed Me
- Redactor
- Super Table
- Typogrify
- Video Embedder

The error still persists when I disable all of them (except Super Table).

**Comment by engram-design** [comment]
Thanks @thulstrup does this occur when you're editing specific entries, or any entries? When you load an entry, or save it? Does it happen for sections that don't have a Super Table field?

When specifically does it occur?

**Comment by engram-design** [comment]
If anymore can provide a screenshot of the full stack trace with devMode on, I can debug further

**Comment by joshuabaker** [comment]
@engram-design I don’t think a stack trace is going to help here as the exception surfacing is thrown by the template loader. As noted in craftcms/cms#4912, due to the `3.3.1.2` changes, the Assets field is [suppressing](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/fields/Assets.php#L705-L709) any underlying exceptions.

I saw [this exception](https://github.com/verbb/super-table/blob/64376fd147dbced22c457561fc4bd034074a1ead/src/elements/SuperTableBlockElement.php#L255) being thrown by an `SuperTableBlockElement` instance with only the `fieldId` set. Briefly looking at the database, all looks present and correct. Is there any reason why that might have been unpopulated?

**Comment by engram-design** [comment]
@joshuabaker If not for the stack trace then when/where is the error occurring? I can't even get it to throw this error, which is what I'm try to recreate. Basically, after the error page that's showing `Twig Template Loading Error – craft\web\twig\TemplateLoaderException
Unable to find the template “_components/fieldtypes/Assets/input”`

Not 100% sure about the second part to your question, and it depends when it occurred and what you were doing. Was it loading an entry to edit, saving, or something else?

Can you advise on your Super Table field setup maybe?

**Comment by engram-design** [comment]
I'm also not sure I follow about the error suppression within [this file](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/fields/Assets.php#L705-L709). I can uncomment those try/catch statements to throw that error, and even throw an exception further up, and it won't affect things from loading okay

**Comment by joshuabaker** [comment]
Here’s a breakdown of what I saw yesterday:
1. To get a folder ID via a call to [`inputSources`](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/fields/Assets.php#L544), the `Assets` field instance [calls `renderObjectTemplate`](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/fields/Assets.php#L706)
1. `View` then [sets the template mode to ‘site’](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/web/View.php#L496)
1. `View` then tries to [get variables from `SuperTableBlockElement`](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/web/View.php#L511)
1. `ownerId` is not set so [throws an exception](https://github.com/verbb/super-table/blob/64376fd147dbced22c457561fc4bd034074a1ead/src/elements/SuperTableBlockElement.php#L255) (`View` therefore doesn’t get to [reset the template mode](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/web/View.php#L555) to ‘cp’)
1. `Assets` [catches that exception](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/fields/Assets.php#L707)
1. But then [throws a different kind of exception](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/fields/Assets.php#L708)
1. Unfortunately, [this exception is caught](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/fields/Assets.php#L808)
1. As the template mode is still ‘site’ and not ‘cp’, the template loader then tries to load the `_components/fieldtypes/Assets/input` template in the wrong template mode

**Comment by engram-design** [comment]
Thanks for the detailed explanation @joshuabaker - was this an existing entry you were editing or a new one? Seems to be an issue with `ownerId` not being set, as you've mentioned

**Comment by joshuabaker** [comment]
Sure thing. It’s a complicated web of calls to traverse.

> was this an existing entry you were editing or a new one?

It was an existing entry.

> Seems to be an issue with `ownerId` not being set, as you've mentioned

If memory serves, only the `fieldId` was set on the `SuperTableBlockElement` instance.

I _think_ the issue is actually unrelated to `3.3.1.2`. It’s just that the [moving `setTemplateMode` call](https://github.com/craftcms/cms/compare/3.3.1.1...3.3.1.2#diff-4422c3de0f12912695426929fd18af29L536-L537) before the element is accessed has allowed this to surface.

**Comment by engram-design** [comment]
Yep, that's what I'm thinking @joshuabaker - its just surfaced the issue. I'll try and investigate further, but might likely need access to one of these installs to see specifically what's going on.

Thanks for your troubleshooting!

**Comment by thulstrup** [comment]
@engram-design I can load existing entries, but I can't edit or create new.
It only happens for entries with Super Table fields.

Here's a stack trace: https://pastebin.com/c5PMG1WY
