### ISSUE TITLE
Super Table as Commerce variant field

### ISSUE THREAD

**Issue by iamtompickering** [engram-design/SuperTable#307]
### Description

I upgraded a site from Craft 2 > Craft 3 recently and since the update, there has been an issue resulting in not being able to save new products in Craft Commerce. It is worth noting that the site is setup with multiple sites. 

I have a Super Table field as a product variant field and it looks like this is where the issue lies. When I remove the field, I am able to create and save new products. But when the field is present, the following error appears.

<img width="2018" alt="Screenshot 2019-10-21 at 15 24 25" src="https://user-images.githubusercontent.com/6592882/67268474-7b32f480-f4ac-11e9-821f-37f48cd03dae.png">

I have tried the following to resolve: 
- Checked the table prefix in .env is "craft" and not "craf", strange that it says "craf_" in the screenshot, but the prefix is definitely correct in the production .env file.
- Ran Super Table fixes - it logged no errors.
- Ran Super Table resave - it logged no errors. 
- Installed Fix FKs plugin, ran that but had no effect. 

### Steps to reproduce
- Create a Super table and include as a variant field in a Commerce product. 
- Create a new product and try to save. 
- Create a new product and try to save.  

### Additional info

- Plugin version: 2.3.0
- Craft version: 3.3.3
- Commerce version: 2.1.13

**Comment by bymayo** [comment]
Just as a follow up to this error - It seems that some SuperTable tables had kept a column called `locale` and an associated foreign key with it, e.g. `craft_supertablecontent_producttabs_elementId_locale_unq_idx`.

I removed this foreign key and the column from the tables that caused the error and it resolves the error.

But my question is now, is this likely to cause any other issues with my removing the foreign key manually in the database?

**Comment by engram-design** [comment]
So firstly, you shouldn't be seeing anything pulling in content from a `craft_supertablecontent_*` table - these were deprecated a _long_ time ago, in favour of `craft_stc_*` due to MySQL table name limits causing all sorts of issues.

This is one of the many fixes the "Content Table Fixes" should sort out for you, but sounds like it hasn't in this case.

@iamtompickering The checking/fixing didn't report anything out of place, and things seemingly went all okay? Its probably safe to delete any craft_supertablecontent_*` table - I just kept them around out of nervousness in deleting content! For some reason, it seems like its trying to save content to both the new and old tables. Strange.

@bymayo There shouldn't be that column, and if there is, it sounds like one of the migrations haven't converted this over to a site column. Its probably not amazing that you removed the foreign key, but its a workable solution for the moment. I don't foresee any deal-breaking issues due to it, for instance.

**Comment by engram-design** [comment]
Closing due to age.
