### ISSUE TITLE
Formatting issues with Field Layout 

### ISSUE THREAD

**Issue by jayhlee** [engram-design/SuperTable#342]
### Description
When "Row Layout" is selected for Field Layout, the field/blocks expand all the way across the control panel. See attached image.

### Additional info

- Plugin version: 2.4.6
- Craft version: 3.4.8

<img width="931" alt="formatting" src="https://user-images.githubusercontent.com/25807445/76045829-0ddfa780-5f13-11ea-9deb-c392281e106c.png">

**Comment by nstcactus** [comment]
In the meantime, you can fix this with the following CSS:
````
.superTable-table.superTable-layout-row {
  table-layout: fixed;
}

.superTable-table.superTable-layout-row .thin.rowHeader {
  width: 15% !important;
  min-width: 130px;
  white-space: initial;
}
````
You can inject it using a [custom module](https://docs.craftcms.com/v3/extend/module-guide.html#app) or the [cp-css plugin](https://plugins.craftcms.com/cp-css).

**Comment by engram-design** [comment]
I'm certainly not seeing this, are there any other field types in the block? Have to set any widths on fields within the Super Table field? I notice there isn't a border around the field, which seems like something's not quite right?

@nstCactus The reason the table isn't fixed with is mostly so that the left-hand labels only take up the required space without line-breaking.

**Comment by nstcactus** [comment]
This was only meant as a quick fix, I would have made a PR if I was sure this was the way to go 🙂.

Regarding other field types, I think a combination of a long enough label somewhere in the table and a [typed link field](https://plugins.craftcms.com/typedlinkfield) (with external links allowed and the ability to append a query string) seems to trigger the bug.

It's also worth noting that my screen resolution is rather high (15 inch display, 1440px wide). On smaller screen the bug is more frequent (a shorter label is enough to trigger it).

<img width="1440" alt="Screenshot 2020-04-01 10 14 06" src="https://user-images.githubusercontent.com/353843/78114535-bb09ea80-7401-11ea-8ff8-39c16abf1dbd.png">

**Comment by engram-design** [comment]
@nstCactus Certainly appreciate the fix nonetheless!

And your example shows the fields indeed going beyond the bounds of the field, but its a little different to the OP, where its being clipped.

I do also plan to refactor the row layout into a non-table element to fix these sorts of things.

**Comment by engram-design** [comment]
I've managed to improve this by switching the row layout to CSS Grid. Its been a long-term plan of mine to do this anyway, as the table-based markup just isn't a good fit in this instance.

See [2.4.7](https://github.com/verbb/super-table/releases/tag/2.4.7)
