### ISSUE TITLE
Question about contentTable property for fields

### ISSUE THREAD

**Issue by davist11** [engram-design/SuperTable#408]
**What are you trying to do?**
Occasionally we see the `contentTable` property of a field change in the project config depending on which developer makes a change locally that would trigger a project config change. I think I tracked it down to this block of code:

https://github.com/verbb/super-table/blob/4f9a302c4c6c8eb1809400e64bd5a6bb5045fa10/src/services/SuperTableService.php#L716-L718

Since the ID could be different across DBs.

**What's your proposed solution?**
I'm not sure! It doesn't seem like it causes issues, but it feels weird for the table name to be consistently changing. Should is be using `uid`? Is this `id` in the table name even important?

**Comment by mildlygeeky** [comment]
Oh man, this - we're frequently seeing the same happen, and it is nerve-racking to say the least.

**Comment by engram-design** [comment]
Yeah, this unfortunately leaves us in a really tricky situation, because we rely on the parent Matrix field to determine the content table. At the time, using the ID was a good idea, before Project Config was even a thing. We can't really use the UID as that would make the table name way too long (an issue in itself), and using the handle of the Matrix field sort of solves this, but there's still issues with a 32 character limit on a table. We'd also need to actively update it when the field changed.

It's reasonably safe, but a bit gross, I'll agree. I'm not quite sure how to tackle this in an easy way, and it's possibly something that won't get fixed properly, due to upcoming Craft 4 changes.

**Comment by davist11** [comment]
Gotcha, appreciate the explanation.
