### ISSUE TITLE
Collapsed matrix-style fields no longer have preview text

### ISSUE THREAD

**Issue by evanwarner** [engram-design/SuperTable#439]
After updating to 2.7.0, all my collapsed Super Table fields using matrix style layout no longer have any preview text on them.

<img width="1178" alt="collapsed-st-fields" src="https://user-images.githubusercontent.com/6453842/144681026-a955364d-a11b-4ff4-b2ba-dab547d2a89f.png">

**Steps to reproduce**
1. Create a Super Table field (top-level or nested in Matrix) using Matrix layout style
2. Generate Super Table blocks and collapse them
3. The collapsed blocks have no information on them

**Additional info**
- Plugin version: 2.7.0
- Craft version:3.7.24
- Multi-site: No

**Comment by evanwarner** [comment]
@engram-design I figured out why this happens. On [this line](https://github.com/verbb/super-table/blob/a82e90bc57401c502405e824f7e53baf05e10cd3/src/resources/src/js/_input.js#L658), the call to `.children('.input')` isn't finding anything because `.input` is no longer a direct child of `.field`. Changing the code to `.find('.input')` fixes this issue.

Looks like this is maybe due to a change in Craft's field rendering markup?

**Comment by gregorterrill** [comment]
@engram-design Any chance this issue will get fixed in the near future? 

We've had to switch all of the Super Table fields for one client to use a different layout option because they're finding the blank collapsed item headers in Matrix layout to be a usability issue. In fields with a lot of items, you basically have to go through expanding them all one-by-one to find the item you're looking for, whereas with a native Matrix field (or Super Table before) you can just see the top field values in the item header bar. 

After changing to Row layout they're complaining that there are so many fields to scroll through when the items aren't collapsible like they are in the Matrix layout (and I agree, it quickly gets pretty overwhelming to look at). And in Table layout some text overflows (possibly because the last thing in the subitems is a third-party Typed Link Field) so it looks sort of broken. Screenshots below for some context.

**Matrix Layout:**
![Screen Shot 2022-03-16 at 2 29 43 PM](https://user-images.githubusercontent.com/1774747/158662343-7b247032-e30b-4ea5-8111-c1cc116e3541.png)

**Row Layout:**
![Screen Shot 2022-03-16 at 2 29 02 PM](https://user-images.githubusercontent.com/1774747/158662345-88063d41-6b86-43da-8fde-5c5628e004c0.png)

**Table Layout:**
![Screen Shot 2022-03-16 at 2 28 22 PM](https://user-images.githubusercontent.com/1774747/158662348-60833635-23b7-4644-9847-fe6d6807fcbe.png)

Anyway, sorry to be pestering but this one's causing us a lot of grief and it sounds from Evan's suggestion above like it might be a relatively straightforward fix?

**Comment by dcplebranch** [comment]
I'd also love if this were fixed. It's pretty confusing to not see any labels on collapsed items. Thanks,

**Comment by stevecomrie** [comment]
> @engram-design I figured out why this happens. On [this line](https://github.com/verbb/super-table/blob/a82e90bc57401c502405e824f7e53baf05e10cd3/src/resources/src/js/_input.js#L658), the call to `.children('.input')` isn't finding anything because `.input` is no longer a direct child of `.field`. Changing the code to `.find('.input')` fixes this issue.

I've submitted your code changes as a Pull Request. Hopefully, that makes it quick and easy to push out an update.

**Comment by engram-design** [comment]
Fixed in [3.0.3](https://github.com/verbb/super-table/releases/tag/3.0.3) thanks @evanwarner and @stevecomrie

**Comment by evanwarner** [comment]
@stevecomrie thanks for doing the PR! I kind of forgot about this bug since I fixed it manually on my sites that use the plugin. 😂

**Comment by stevecomrie** [comment]
> @stevecomrie thanks for doing the PR! I kind of forgot about this bug since I fixed it manually on my sites that use the plugin. joy

Yeah ... I did that once. And then my build and deployment process clobbered my edits. And then I had to blow away my vendor directory to test something else and that clobbered my edits again.

So I just figured it would be best to go to the source :)

Thanks for figuring out what the issue was in the first place.
