### ISSUE TITLE
Should we worry about a table name change in .yaml files?

### ISSUE THREAD

**Issue by gbowne-quickbase** [engram-design/SuperTable#446]
**Description**
Our handful of devs regularly apply develop branches back on their local environments and sometimes when they make changes to other parts of a field, we get these sorts of changes in our PRs (or MRs since we are on gitlab) 

![image](https://user-images.githubusercontent.com/39066452/148074570-cf558f27-ef2e-40d0-a56f-d9432aa92a42.png)

Is this something that will cause issues upstream if the production table was created with a different number?

**Steps to reproduce**
1. Dev adds a supertable field, commits changes
2. Different dev pulls or merges, applies changes
3. Second dev pushes up code and we see table numbers change

**Additional info**
- Plugin version: 2.7.0
- Craft version: 3.7.26 
- Multi-site: No

**Comment by simonmeulenbeek** [comment]
I'm very interested in this as well.. What I'm seeing sometimes is even more strange IMO; when we make a change to some field, we see that the contentTable of an UNRELATED FIELD is updated? I really have a hard time seeing the use of this, especially because we're constantly having problems with config for dev/prod getting out of sync. 

Can a dev give clarity about this?

**Comment by gbowne-quickbase** [comment]
My devs are still seeing this problem, like every time. Is there danger in losing the content in those tables?
<img width="608" alt="image" src="https://user-images.githubusercontent.com/39066452/183109773-d692e124-cc38-4825-8034-1843348dba03.png">

**Comment by gbowne-quickbase** [comment]
My team did some look into this and the `project-config/apply` perform a table rename, so it's all good. There just might be some tables that renumber more often as work happens on them
