### ISSUE TITLE
Asset dont be saved when the field is added after a first save.

### ISSUE THREAD

**Issue by stephanedemotte** [engram-design/SuperTable#476]
**Description**

Hello when i have asset field inside a super table, the asset field don't want to be save.

**Steps to reproduce**
1. Create a super table with a text field (make it static field)
2. Add the field inside a Category
3. Create a category and fill the text field
4. add an asset field inside the super table field
5. try to add and asset inside the asset field and save
6. the asset is not saved

**Additional info**
- Plugin version: 3.0.0-beta.5
- Craft version: 4.0.4
- Multi-site: No

**Comment by engram-design** [comment]
I can't replicate this sorry, and I've tried a few different layouts options just in case.

Our of interest, is this _only_ when adding an asset field, or the same situation for other fields, when adding to a Super Table field that already has a value?

**Comment by stephanedemotte** [comment]
https://user-images.githubusercontent.com/2158130/173180719-39647779-7891-4a93-bb17-15ea6edb398b.mov

**Comment by engram-design** [comment]
Hmmm, this actually seems an issue with saving field content in general, only after applying it from a provisional draft. I was testing by saving instantly, because waiting for the provisional draft to be saved (where you see the "Showing your unsaved changes" notice). But after making changes and waiting for that notice and applying save, no changes are saved - even for the text field.

But I'm also noticing the same behaviour with Matrix, so may need to investigate further.

**Comment by mmikkel** [comment]
Looks a lot like the issue described in https://github.com/craftcms/cms/issues/11419.

**Comment by engram-design** [comment]
Good pick @mmikkel we've made that same change on our end in the `craft-4` branch.

**Comment by stephanedemotte** [comment]
@engram-design new release soon ?

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.6](https://github.com/verbb/super-table/releases/tag/3.0.0-beta.6)
