### ISSUE TITLE
Table layout overflows container

### ISSUE THREAD

**Issue by marionnewlevant** [engram-design/SuperTable#59]
I worked around this by adding `.superTableContainer table { table-layout: fixed; }` with cpcss plugin.
![overflowingtable](https://cloud.githubusercontent.com/assets/695477/13617024/7b438bda-e531-11e5-9c16-393744cd964f.png)

**Comment by engram-design** [comment]
Thanks for submitting this - I'll work on a proper fix, as noted in [PR#48](https://github.com/engram-design/SuperTable/pull/48) there are some layout issues when using `table-layout: fixed;`

**Comment by sephorra** [comment]
I added percentage widths onto the th cells of the table header as well which helped with the issue in PR #48 

e.g. 
.superTable th.header { width: 90%}
.superTable th.header[colspan="2"] { width: 10%}

It seems to work but I haven't done any extensive testing (or cross browser testing) to see if it causes any other issues.

**Comment by engram-design** [comment]
@sephorra, Thanks, that's a pretty good solution. Tested in all major browsers (that Craft supports) and responsively (to a degree).

BTW - this does seem to be only an issue with an inner Matrix field, and a Table layout. Now fixed in the latest [master](https://github.com/engram-design/SuperTable).
