### ISSUE TITLE
Setting Column Width Doesn't Work as Expected

### ISSUE THREAD

**Issue by mikevaux** [engram-design/SuperTable#76]
When creating a SuperTable configuration, when setting the width of each column, it doesn't seem to have any effect.

I think this may be to do with the width of the `<th>`s in `<thead>`, as if I Inspect the table when creating an entry and delete `<thead>` altogether, the widths of the columns seem to respect the values I entered.

As a side note (and I am not sure if it was ever intended to do this), if I set the width to a percentage value, the width of the `<td>` is output as [value]%px, e.g. if I set it to 20%, it is output as 20%px (which obviously doesn't work).

Thanks so much for SuperTable by the way.. it's great!

**Comment by engram-design** [comment]
@mikevaux Yep, there were some changes a little while back that broke this (due to `table-layout: fixed` for other issues), but this has been corrected. Additionally, you can provide width in either pixels or percentage - unit-less will default to percentage.

Fixed in the [0.4.7 release](https://github.com/engram-design/SuperTable/releases/tag/0.4.7).
